/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class twisk_simulation_Simulation */

#ifndef _Included_twisk_simulation_Simulation
#define _Included_twisk_simulation_Simulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     twisk_simulation_Simulation
 * Method:    start_simulation
 * Signature: (III[I)[I
 */
JNIEXPORT jintArray JNICALL Java_twisk_simulation_Simulation_start_1simulation
  (JNIEnv *, jobject, jint, jint, jint, jintArray);

/*
 * Class:     twisk_simulation_Simulation
 * Method:    ou_sont_les_clients
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_twisk_simulation_Simulation_ou_1sont_1les_1clients
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     twisk_simulation_Simulation
 * Method:    nettoyage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_twisk_simulation_Simulation_nettoyage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
